name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Set up Python
      uses: actions/setup-python@v2.4.1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest --cov-report term-missing --cov=main tests/

    - name: Run Flake8 linting
      run: |
        pip install flake8
        flake8 --format=html --htmldir=flake8_report your_module

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: Test Report
        path: |
          pytest-report.html
          flake8_report/
